### necessario ter a extensão REST Client no vscode

### RENTS
### Create
POST http://localhost:3000/rents/create
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7ImlkIjoiNjE0MTMyOGQzZmRkZDQ1Y2IxNDJkZDA2IiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTYzMTc1NjM0NywiZXhwIjoxNjMxNzU5OTQ3fQ.OlPi_qRWfK3O6QEAuKFDfI1ssvx4IposcTeZ8vVAX-s

{
    "idUser": "6546546",
    "idMovies": ["613eac2263be4cfb259e8309"],
	"originalPrice": "10.00"
}

### List
GET http://localhost:3000/rents
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7ImlkIjoiNjE0MTMyOGQzZmRkZDQ1Y2IxNDJkZDA2IiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTYzMTc1NDM0MCwiZXhwIjoxNjMxNzU3OTQwfQ.HD0pMVXWUXcWYo4rD4RGGYKFEmLgtyF2cD3Jhg23byI

### Update
PUT http://localhost:3000/rents/update
Content-Type: application/json

{
	"id": "613ecc341b02cdb8a62e853d", 
    "update": {
        "currentPrice": "30"
    }
}

### Finish a rent
PUT http://localhost:3000/rents/rentEnd
Content-Type: application/json
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7ImlkIjoiNjE0MTMyOGQzZmRkZDQ1Y2IxNDJkZDA2IiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTYzMTc1NDM0MCwiZXhwIjoxNjMxNzU3OTQwfQ.HD0pMVXWUXcWYo4rD4RGGYKFEmLgtyF2cD3Jhg23byI

{
	"id": "6142a04d3f419a4e9848a527",
    "data": {"rentDate": "2021-09-16T01:39:25.410Z", "originalPrice": "10.00"}
}

### Delete
DELETE http://localhost:3000/rents/6142a04d3f419a4e9848a527
auth-token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhdXRoIjp7ImlkIjoiNjE0MTMyOGQzZmRkZDQ1Y2IxNDJkZDA2IiwiaXNBZG1pbiI6dHJ1ZX0sImlhdCI6MTYzMTc1NjM0NywiZXhwIjoxNjMxNzU5OTQ3fQ.OlPi_qRWfK3O6QEAuKFDfI1ssvx4IposcTeZ8vVAX-s
