### necessario ter a extensão REST Client no vscode

### MOVIES
### Create
POST http://localhost:3000/movies/create
Content-Type: application/json

{
    "title": "Godfather",
    "director": "Francis Coppola",
    "price": "5",
    "stock": "5"
}

### List
GET http://localhost:3000/movies

### Update
PUT http://localhost:3000/movies/update
Content-Type: application/json

{
    "id": "613eb5d0cbae2ad15581c685",
    "update": {
        "title": "interestelar"
    }
}

### Delete
DELETE http://localhost:3000/movies/613eb1a16b9dbb2664a760d8
